name: GETTY Message

on:
  workflow_dispatch:

jobs:
  build:
    name: Send Message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Send Kanban Message
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#E94579'
          SLACK_ICON: https://download.logo.wine/logo/Getty_Images/Getty_Images-Logo.wine.png
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: '헤헷'
          MSG_MINIMAL: true
          SLACK_USERNAME: 게티이미지 사진전 같이가서 극락간 유령
          SLACK_MESSAGE: '같이 가줘서 고마워 이제 그만 나는 이세카이를 떠날게'
