name: TMI Message

on:
  schedule:
    - cron:  '40 12 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Send Message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Send Kanban Message
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#E94579'
          SLACK_ICON: https://user-images.githubusercontent.com/54518925/155890128-11bcd81f-b96a-4090-9313-c7a85197ac13.png
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: '다들....행복해?'
          MSG_MINIMAL: true
          SLACK_USERNAME: H2O
          SLACK_MESSAGE: '오늘 다들 뭐했어?'

